using System.Collections;
using System.Collections.Generic;
using SOSXR.EnhancedLogger;
using UnityEngine;


namespace SOSXR.Talkies
{
    /// <summary>
    ///     A class that keeps track of which pins have been used by the PinController, and sets those LOW after a short time interval
    ///     This to try to keep heat generated by some components to minimum.
    /// </summary>
    [RequireComponent(typeof(PinController))]
    public class SafetyPin : MonoBehaviour
    {
        [SerializeField] [Range(1, 60)] private int m_setLowAfterSeconds = 30;
        [SerializeField] [HideInInspector] private PinController _pinController;
        private readonly float _checkDelay = 1f;

        private readonly List<float> _safetyPin = new();


        private void OnValidate()
        {
            if (_pinController == null)
            {
                _pinController = GetComponent<PinController>();
            }
        }


        private void OnEnable()
        {
            _pinController.OnPinSetEvent += StartTimer;
        }


        private void Start()
        {
            this.Info($"{nameof(SafetyPin)} is initialized. It will turn used pins LOW after {m_setLowAfterSeconds} seconds.");

            StartCoroutine(TimeCheckerCR());
        }


        /// <summary>
        ///     Called whenever a pin is SET via <see cref="PinController"/>. Starts a countdown
        ///     timer for pins driven HIGH; resets the timer when a pin is driven LOW.
        ///     The timer is only started once per pin — refreshing HIGH will not reset the countdown.
        /// </summary>
        /// <param name="pinNumber">GPIO pin number being set.</param>
        /// <param name="value"><c>true</c> when the pin is driven HIGH; <c>false</c> when LOW.</param>
        private void StartTimer(int pinNumber, bool value)
        {
            if (_safetyPin.Count <= pinNumber)
            {
                _safetyPin.AddRange(new float[pinNumber + 1 - _safetyPin.Count]);
            }

            if (!value)
            {
                _safetyPin[pinNumber] = 0;

                return;
            }

            if (_safetyPin[pinNumber] != 0)
            {
                return;
            }

            _safetyPin[pinNumber] = Time.time + m_setLowAfterSeconds;
        }


        private IEnumerator TimeCheckerCR()
        {
            for (;;)
            {
                yield return new WaitForSeconds(_checkDelay);

                for (var i = 0; i < _safetyPin.Count; i++)
                {
                    if (_safetyPin[i] == 0)
                    {
                        continue;
                    }

                    if (_safetyPin[i] <= Time.time)
                    {
                        this.Info($"Setting pin {i} to LOW because it has been too HIGH for too long.");

                        _pinController.SetPin(i, false);
                        _safetyPin[i] = 0;
                    }
                }
            }
        }


        /// <summary>
        ///     Immediately drives every tracked pin LOW, regardless of their timer state.
        ///     Called on disable to ensure hardware is left in a safe state.
        /// </summary>
        private void HardDisableAllKnownPins()
        {
            for (var i = 0; i < _safetyPin.Count; i++)
            {
                _pinController.SetPin(i, false);
            }
        }


        private void OnDisable()
        {
            HardDisableAllKnownPins();

            _pinController.OnPinSetEvent -= StartTimer;

            StopAllCoroutines();
        }
    }
}